version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'data.redis:/data'
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  websocket:
    image: dlareg/websocket:1.0
    container_name: websocket
    ports:
      - '${FORWARD_WEBSOCKET_PORT:-3000}:3000'
    networks:
      - app-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  app-network:
    driver: bridge
volumes:
  data.redis:
    driver: local
